# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
addons:
  apt:
    packages:
      - libv8-3.14-dev
r: release
r_packages:
 - DiagrammeRsvg
cache: packages
latex: false
