// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// count_precedence
DataFrame count_precedence(CharacterVector cases, IntegerVector activities);
RcppExport SEXP _heuristicsmineR_count_precedence(SEXP casesSEXP, SEXP activitiesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type cases(casesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type activities(activitiesSEXP);
    rcpp_result_gen = Rcpp::wrap(count_precedence(cases, activities));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_heuristicsmineR_count_precedence", (DL_FUNC) &_heuristicsmineR_count_precedence, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_heuristicsmineR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
