# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

count_length_two_loops <- function(cases, activities) {
    .Call(`_heuristicsmineR_count_length_two_loops`, cases, activities)
}

count_precedence <- function(cases, activities, lead) {
    .Call(`_heuristicsmineR_count_precedence`, cases, activities, lead)
}

